name: CI/CD Pipeline for DemoWeb

on:
  pull_request:
    branches:
      - development
      - qa_split
  push:
    paths-ignore:
      - '.github/**'
      - '*.md'
    branches:
      - develop
      - qa_split
      - qa
      - main

jobs:
  deploy_develop:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código fuente
        uses: actions/checkout@v4

      - name: Configurar entorno
        run: echo "Configurando código para develop"

      - name: Configurar despliegue
        run: echo "configurando código en el ambiente de develop"

  deploy_qa_split:
    if: github.ref == 'refs/heads/qa_split'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código fuente
        uses: actions/checkout@v4

      - name: Configurar entorno
        run: echo "Configurando código para qa_split"

      - name: Configurar despliegue
        run: echo "Configurar código ambiente de qa_split"

  deploy_qa:
    if: github.ref == 'refs/heads/qa'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código fuente
        uses: actions/checkout@v4

      - name: Configurar entorno
        run: echo "Configurando código para qa"

      - name: Configurar despliegue
        run: echo "Configurando código en el ambiente de qa"
