name: Deploy Develop to QA

on:
  workflow_dispatch: 
  pull_request:
    branches:
      - qa
  push:
    branches:
      - qa

jobs:
  deploy_qa:
    runs-on: windows-latest
    steps:
      - name: Checkout código fuente
        uses: actions/checkout@v4

      - name: Configurar entorno QA
        shell: pwsh
        run: |
          Write-Output "Configurar código para QA"

      - name: Configurar entorno en QA
        shell: pwsh
        run: |
          Write-Output "Configurar código Develop en QA"
